### ISSUE TITLE
Initialization of “app” from “@microsoft/teams-js” is timing out

### ISSUE THREAD

**Issue by shubh30126** [OfficeDev/microsoft-teams-library-js#1181]
**version:** “@microsoft/teams-js” : "2.0.0-beta.4-dev.9" 
**Error thrown:** Teams js method app.initialize() `Error: SDK initialization timed out.` 
**User Agent of Popup window:** Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Teams/1.5.00.4683 Chrome/85.0.4183.121 Electron/10.4.7 Safari/537.36

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will update you.

**Comment by laduma-adamc** [comment]
Is there any more follow up to this? 
We are having the same issue on almost all Windows clients.

version: “@microsoft/teams-js” : "2.0.0-beta.7"
Error thrown: Teams js method app.initialize() Error: SDK initialization timed out.

**Comment by laduma-adamc** [comment]
Since updating to stable V2.0.0 we are still having this issue.

**Comment by Meghana-MSFT** [comment]
are you using this one - https://www.npmjs.com/package/@microsoft/teams-js ?

**Comment by laduma-adamc** [comment]
> Could you please confirm if you are using this one - https://www.npmjs.com/package/@microsoft/teams-js ?

Yes we are.

We have also refined when the issue is timing out.
If we are in a meeting, and in a side panel, or in a shared meeting stage, we reliably call the `app.initialize()` and it will work really quickly.

If however we are in a content page, or in the configure page, when we add our app to the meeting, then it times out and says that the action was

**Comment by Meghana-MSFT** [comment]
We tried this at our end with the CDN link and it seems to be working fine, are you using it through CDN link or importing the modules?

**Comment by AE-MS** [comment]
Hi @laduma-adamc, we've been looking into your issue and I was hoping you could provide a few more details that might help us reproduce the problem to identify the issue.

If I understand correctly, in your app you call `authentication.authenticate` to a custom page in your app, which then redirects to a login page for your SaaS platform. After logging in, the SaaS platform site redirects back to your custom page (still executing in the popout) and that page tries to call `app.initialize()`, and in certain circumstances that call times out.

Do I have that flow correct?

And am I correct that the only circumstances in which that call to `app.initialize()` times out is when your app is running from a personal tab (the `contentUrl` value in the `staticTabs` section of the manifest) started from the app bar on the side of teams, or a configuration tab (the `configurationUrl` property in the `configurableTabs` section of the manifest)?

**Comment by laduma-adamc** [comment]
@Meghana-MSFT we are importing the modules to use in a React application, hosted in azure static webapps.

@AE-MS 

1. we import `authentication` from the `@microsoft/teams-js` package, and call `authentication` which loads an inital auth start page that is part of our teams application (still in the popout), 
2. The poput then redirtects to our login page for our SaaS platform, which logs the user in.
3. Then redirects back to our teams application, to finalise the login process.
4. In the finalisation page, still in the popup, we load `app` from the `@microsoft/teams-js` package, and call `initialize()`
5. At this point is when it it is failing to initalise, and we have a timeout after 5 seconds.

Currently this only happens if you attempt to log into the application from the `configurableTabs` `configurationUrl` and the `content` view in a meetings details page. We dont have any personal tabs or channel tabs yet in our application, only a meeting extension, and it is usable in the `Side Panel`, `Shared Meeting Stage`, and the `Details` page.

thanks,
Adam

**Comment by shubh30126** [comment]
@Meghana-MSFT Any update on this?

**Comment by AE-MS** [comment]
> @Meghana-MSFT we are importing the modules to use in a React application, hosted in azure static webapps.
> 
> @AE-MS
> 
> 1. we import `authentication` from the `@microsoft/teams-js` package, and call `authentication` which loads an inital auth start page that is part of our teams application (still in the popout),
> 2. The poput then redirtects to our login page for our SaaS platform, which logs the user in.
> 3. Then redirects back to our teams application, to finalise the login process.
> 4. In the finalisation page, still in the popup, we load `app` from the `@microsoft/teams-js` package, and call `initialize()`
> 5. At this point is when it it is failing to initalise, and we have a timeout after 5 seconds.
> 
> Currently this only happens if you attempt to log into the application from the `configurableTabs` `configurationUrl` and the `content` view in a meetings details page. We dont have any personal tabs or channel tabs yet in our application, only a meeting extension, and it is usable in the `Side Panel`, `Shared Meeting Stage`, and the `Details` page.
> 
> thanks, Adam

Thanks for providing the extra detail. I double-checked that my attempt to reproduce the problem matched what you are doing, but unfortunately, I was not able to reproduce the issue. As a result, I'm about to publish some instructions for you on how to enable logging so you can run your scenario with logging on and we can use that to try and troubleshoot. Be back with those instructions within a day!

**Comment by Meghana-MSFT** [comment]
> @Meghana-MSFT Any update on this?

Engineering team is looking into it.

**Comment by laduma-adamc** [comment]
Hi, 

Please find attached two sets of debug logs, `app_page.txt` are the logs from the page we launch the auth window from, and `auth_page.txt` are the logs from the auth window.

[app_page.txt](https://github.com/OfficeDev/microsoft-teams-library-js/files/8845179/app_page.txt)
[auth_page.txt](https://github.com/OfficeDev/microsoft-teams-library-js/files/8845181/auth_page.txt)

Thanks,

**Comment by AE-MS** [comment]
> Hi,
> 
> Please find attached two sets of debug logs, `app_page.txt` are the logs from the page we launch the auth window from, and `auth_page.txt` are the logs from the auth window.
> 
> [app_page.txt](https://github.com/OfficeDev/microsoft-teams-library-js/files/8845179/app_page.txt) [auth_page.txt](https://github.com/OfficeDev/microsoft-teams-library-js/files/8845181/auth_page.txt)
> 
> Thanks,

Thank you so much for providing the logs! Using the information from them, we have some idea what might be going on. We are investigating and will get back to you ASAP.

**Comment by laduma-adamc** [comment]
Thanks,

Any more help that you need, please let me know, we are being held up by this issue.

Thanks.

**Comment by AE-MS** [comment]
Just wanted to let you know that we're still looking to ensure we have the right people investigating the problem so we can get to the bottom of the issue. @nwojod-MSFT is working to find the right contact and can update this issue.

**Comment by nwojod-MSFT** [comment]
@laduma-adamc we did get in touch with the right team and they are still investigating the problem. I will update this thread once I get an ETA for resolution.

**Comment by shubh30126** [comment]
@nwojod-MSFT Any update on this?

**Comment by nwojod-MSFT** [comment]
Hello @shubh30126, I am yet to get any update from the team. The team raised an incident report and are currently working on resolving the issue; however, no ETA has been given.

**Comment by nwojod-MSFT** [comment]
@laduma-adamc and @shubh30126 got an update from the team, unfortunately, the issue has a proposed fix in Electron 16 based Teams. The current estimate for rollout on Windows is end of September.

**Comment by shubh30126** [comment]
@nwojod-MSFT Do we have an ETA for Mac based Teams App as well?

**Comment by nwojod-MSFT** [comment]
@shubh30126 Mac will likely rollout before Windows. I will confirm ETA and update this post.

**Comment by CKGHarju** [comment]
I am leaving this here if it might be any help to @[nwojod-MSFT](https://github.com/nwojod-MSFT) [AE-MS](https://github.com/AE-MS) [Meghana-MSFT](https://github.com/Meghana-MSFT) for narrowing down the issue, which seems to be network related?

@[shubh30126](https://github.com/shubh30126) I've encountered the same error with the authentication flow both on Windows 10 and and Mac. On the last page of the authentication flow when calling `microsoftTeams.app.initialize` it timeouts and we get the following error `Error: SDK initialization timed out`, preventing us from ever reaching `microsoftTeams.authentication.notifySuccess`.

I've tried every trick I could think of without success. Weirdly when passing our application zip file to my coworkers (working on different networks) they would not encounter the same error. 

I managed to resolve the issue on my clients when switching to a different network.

**Comment by guillaumemeyer** [comment]
Got the same issue here. Any news?

**Comment by guillaumemeyer** [comment]
@laduma-adamc @tiennguyen1293 , were you able to find a solution on your side? Or you're still waiting for a fix from MS?

**Comment by guillaumemeyer** [comment]
Be careful @tiennguyen1293 . As the Teams client is being upgraded to Electron 16, teams-js v1.x is already not working anymore on certain Mac desktop clients, and Windows soon (despite anything you can read about compatibility for deprecated methods of the SDK...).

**Comment by nwojod-MSFT** [comment]
@guillaumemeyer , @tiennguyen1293 Mac rollout for E16 version is 100% and Windows is still about 50%. The same estimate for 100% Windows is end of September. You should be able to update your Mac client to get the E16 version.

**Comment by AE-MS** [comment]
> Be careful @tiennguyen1293 . As the Teams client is being upgraded to Electron 16, teams-js v1.x is already not working anymore on certain Mac desktop clients, and Windows soon (despite anything you can read about compatibility for deprecated methods of the SDK...).

Hi @guillaumemeyer! Could you provide some more details about which functionality in TeamsJS currently marked as deprecated is not working anymore? Ideally if you could open a new github issue with an example, we could use that to investigate. Any deprecated methods still in the SDK remain supported and if you've found deprecated methods that have stopped working, we would treat that as a bug to be fixed. Thanks!

**Comment by tiennguyen1293** [comment]
Hi teams, any update on this issue, I'm waiting to implement Teams v2. :(

**Comment by sumit12690** [comment]
Hi team, is there any update on this issue? I am facing the same issue in ms-teams SDK version 2.3.0.

Screenshot Attached

<img width="295" alt="Screenshot 2022-09-27 at 3 44 57 PM" src="https://user-images.githubusercontent.com/3096021/192499773-c27d6012-3958-44ee-a81a-56a922dc19cb.png">

**Comment by sumit12690** [comment]
@AE-MS , @Meghana-MSFT : Can you please let me know the ETA of the this issue?

**Comment by Meghana-MSFT** [comment]
@sumit12690 - Please refer https://github.com/OfficeDev/microsoft-teams-library-js/issues/1181#issuecomment-1224136708. Thank you.

**Comment by sumit12690** [comment]
@AE-MS , @Meghana-MSFT : Can you please let me know the release date of the new version?

**Comment by NuxXDev** [comment]
> @laduma-adamc and @shubh30126 got an update from the team, unfortunately, the issue has a proposed fix in Electron 16 based Teams. The current estimate for rollout on Windows is end of September.
What is the status of the Teams Electron 16 release for Windows?  September has now passed and there is still no fix for this issue.

**Comment by nwojod-MSFT** [comment]
@sumit12690, @NuxXDev, got new update. The team encountered a problem that needs to be resolved before the fix can be released. Release for Windows is expected in coming days, but no exact date yet. I will update this thread once the release date is finalized.

**Comment by Alcip** [comment]
@nwojod-MSFT any update on the issue? More and more users are facing this issue.

**Comment by nwojod-MSFT** [comment]
@Alcip the rollout is currently 75%. The team is anticipating 100% rollout by end of week if no new issues are identified.

**Comment by NuxXDev** [comment]
My Teams Windows Client updated to Version 1.5.00.28361 / Electron 16.2.8, does this mean it should have the fix?  I haven't verified yet.

**Comment by Alcip** [comment]
have received an update here is the version You have Microsoft Teams Version 1.5.00.28567 (64-bit). It was last updated on 21/10/2022. And I'm still seeing the issue.

**Comment by nwojod-MSFT** [comment]
@Alcip thank you for the update. Please can you provide a snippet of the error message you are seeing? I will share this information back with the engineering team to identify why the issue persists. Thanks

**Comment by cgvalayev** [comment]
Hey @nwojod-MSFT can you please let us know starting with which Teams version the fix is applied? Also, is restart or reinstall of the Teams desktop app required?

**Comment by NuxXDev** [comment]
Can we assume this has been pushed out to all Windows Clients by now?  The issue seems resolved but before releasing anything need to be sure all Windows Clients have the fix.

**Comment by nwojod-MSFT** [comment]
Hi @cabevavy the team is still running some tests to ensure the issue is resolved for all users. The current version of Teams to have this fix is 1.5.00.28567, and Electron 16.2.8.

**Comment by cgvalayev** [comment]
Can't tell how many people got update but the issue doesn't seem to go away: 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/88786064/202587094-6ae019e4-0d65-48f2-a7c0-7cee27012129.png">

**Comment by miron4dev** [comment]
Hi @nwojod-MSFT 

The issue is still reproducible for `1.5.00.32154, last updated on 18.11.2022.` 
Setup:
macOS Monterey 12.5.1
"@microsoft/teams-js": "^2.5.0"

```javascript
ms.app.initialize().then(() => ms.authentication.notifySuccess())
```

The issue is blocking us from upgrading to SDK 2.x

**Comment by zaishuiyufang** [comment]
Hi @nwojod-MSFT
I'm also facing this problem，The issue is blocking us from upgrading to SDK 2.x
![image](https://user-images.githubusercontent.com/34640860/203891351-09a596fd-7949-4055-ab39-699de2e7ac8e.png)
However, the problem that I downgraded to version 1.10.0 can be solved.

**Comment by mustafasezer** [comment]
Hi @nwojod-MSFT I recently found out that `app.initialize()` works without problems, if I upload a custom tab app with the page served on my local machine via tunnel (like ngrok, I use loca.lt). However, if I deploy my app to aws amplify, the initialization times out. I tried it with teams-js versions 1.10.0, 2.4.1 and latest, all of them have the same behaviour.

**Comment by miron4dev** [comment]
Hi @nwojod-MSFT @Meghana-MSFT 

Do you have any updates?

**Comment by JohnFTitor** [comment]
Here with SDK 2.7.1, tested on Linux, Ubuntu, and Chrome web version of MSTeams, facing the exact same issue for a personal app
![image](https://user-images.githubusercontent.com/74314917/211683775-10d19896-c63d-49d3-a9d9-af88f5dd683e.png)

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
We will check on this and let you know the updates.

**Comment by Thommurgia** [comment]
Hello everyone, 
I'm facing the same problem today, do someone have found a solution ?
I tried to use msal library for angular to authenticate my customer but msal popup is blocked by teams desktop application. The solution was to use @microsoft/ms-teams but i'm timed out using app.initialize();

If someone have another solution to obtain customer token in vue to use Microsoft Graph api i'm open to solutions !
@Meghana-MSFT

**Comment by sommerlilie** [comment]
Hi, 

we are also encountering the issue. It happened "over night". Local env works, deployed one (via Teams Toolkit) not.

**Comment by sommerlilie** [comment]
I found a solution by re-deploying the App. No Code changes at all. It seems to be an issue on the Azure hosting side. At least for us.

**Comment by ScottRJones** [comment]
We are also having frustrating issues with **SDK initialization timed out** error when trying to call **microsoftTeams.app.initialize();** from our Saas application. 

Our aim is to develop a Microsoft Teams Message Extension capable of communicating with our Saas application after authentication with it. 

Upon debugging the Teams Bot we install our Teams App:

![image](https://user-images.githubusercontent.com/45169231/226314664-2ca877f9-4b47-4faa-a6af-1958135799c1.png)

We are then directed to a chat window where the extension is installed:
![image](https://user-images.githubusercontent.com/45169231/226315074-090536a8-9166-4bf4-a103-0be153b6e6e1.png)

Upon clicking an action button we are prompted to login:
![image](https://user-images.githubusercontent.com/45169231/226315358-b7591cac-21d6-42b2-bc25-61405187ca5f.png)

The sign in button then takes you to our application for authentication:
![image](https://user-images.githubusercontent.com/45169231/226315900-02b865b2-976e-48e1-8308-bf2a6acf7ea1.png)

Upon successful login within our application a JavaScript file is then loaded with the following:
`microsoftTeams.app.initialize();`

This is failing after a few seconds with
`Uncaught (in promise) Error: SDK initialization timed out.`

We are using the following package:
` "@microsoft/teams-js": "^2.9.1"`

And are running ngrok to allow the connection to Local Teams Debug and our Local application Debug. 

We have been hitting our head against a wall for days with this now and cannot seem to get past this error, when everything we have done is seemingly correct. It seems that many others are also having the same problem especially in recent days and weeks.

Can anyone provide any support or update on this issue please?

Thank you
Scott

**Comment by ScottRJones** [comment]
Hi @sommerlilie , thank you for your reply and suggestion.  We will try this in the next day or two and report back. 
Kind regards
Scott

**Comment by Thommurgia** [comment]
Hello everyone,

For me it's now working. To be honest I'm still student and I don't really understand why it's working...

But, if I understand a bit what's happening in my case, I moved the Authentication.authenticate method in the highest level of my app and now it's working. 

Before, I called this method in one of my component where I wanted to authenticate my user. And now I'm doing this in the entry class of my program.

I'm working on a teams tab app, created with Teams Toolkit in Visual Studio Code, this app is generated in react by the toolkit.
I moved this method from a component to my index.tsx file. I think it's this changing that made me solve my problem but to be honest I'm not sure.

I hope this can help some of you, don't hesitate to ping me if you want more informations.

Have a nice day,
Thomas

**Comment by RishavNice** [comment]
Hi @shubh30126 

Did you solve the issue. Please reply. We're facing the same issue.

**Comment by vvolodin** [comment]
any updates on this? it's been almost a year.

**Comment by Thommurgia** [comment]
Nothing is working for me but I can add some informations. 

I'm using this method in a Teams tab application, this is built in react with Teams toolkit from Visual Studio Code.
The application start in a class named index.tsx and in this class i'm using app.Initialize().then() ... 

When I launch the application in teams browzer it works properly. When I launch the application in teams desktop it doesn't work properly at a first step but when i modify something in the code and the "hot reload" reload the page then app.initiliaze works properly.

I don't understand what is the problem with this method but the behaviour is really strange.

Thomas

**Comment by nwojod-MSFT** [comment]
Hello all, apologies that this issue has not been resolved for such a long time. Our team has been actively working to identify the root cause of the problem in order to fix it. Unfortunately, the initial proposed solution we had in Electron 16 did not fix the bug, so our engineering team has been working hard to come up with a new solution. While we don't have a clear ETA on when this will be resolved, we want to assure everyone that we are still working tirelessly to fix the issue, and we will provide updates to the community as soon as we can identify the root cause. Thank you for your patience.

**Comment by integrationworktual** [comment]
Morning @ScottRJones could you please provide support to sort out this issue unhandled (in promise) Error: SDK initialization timed out.
![sdk error](https://user-images.githubusercontent.com/131451049/233615361-83fb491a-6361-48c4-b962-7eda4fa84f48.png)

after successfully login in javascript  , calling app.initialize().then(()=> {
let token ='sample token'
authentication.notifySuccess(token )
})
getting Uncaught (in promise) Error: SDK initialization timed out. after  5sec
am trying to sort out this issues past one week 

thanks,

**Comment by integrationworktual** [comment]
@nwojod-MSFT  would you please  any update on this issue.

thanks,

**Comment by ScottRJones** [comment]
> Morning @ScottRJones could you please provide support to sort out this issue unhandled (in promise) Error: SDK initialization timed out. ![sdk error](https://user-images.githubusercontent.com/131451049/233615361-83fb491a-6361-48c4-b962-7eda4fa84f48.png)
> 
> after successfully login in javascript , calling app.initialize().then(()=> { let token ='sample token' authentication.notifySuccess(token ) }) getting Uncaught (in promise) Error: SDK initialization timed out. after 5sec am trying to sort out this issues past one week
> 
> thanks,

Hi @integrationworktual 
We are still having the same issue here and are awaiting a response from @nwojod-MSFT .
@nwojod-MSFT - can you provide an update of where a fix for this is up to now please? Thank you.

Kind regards
Scott

**Comment by integrationworktual** [comment]
@nwojod-MSFT regarding team tab module working on local debug mode only not able get a authenticate.notifysuccess() message after login third party oauth could provide a valuable feedback 

regards,

**Comment by ScottRJones** [comment]
@nwojod-MSFT @ChetanSharma-msft @Meghana-MSFT  - Please can you provide an urgent update on this? It has now been a year since this issue was first reported and we seem no closer to resolving it which is very frustrating. Thank you.

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by kaneg** [comment]
We have the same issue: 
```
Uncaught (in promise) Error: SDK initialization timed out.
    at n.initialize (app.ts:570:9)
    at Module.qt (publicAPIs.ts:45:7)
    at messages?type=loginCallback:10:20
```

**Comment by sschoeb** [comment]
We are also facing this issue since the upgrade from 1.x to 2.11.0. Guess the only workaround for now is to downgrade to an older version. 

@ChetanSharma-msft Any update on that would be great. Thanks.

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by nwojod-MSFT** [comment]
Hello all, apologies for the delayed reply. We made a fix that we think might address this issue; it's in Teams **_version 1.0.0.2023052414_** (web client). Can you all try this and see if you still experience the problem reported here? Thanks.

**Comment by iliapir2** [comment]
I'm having this issue too, it would be great if library will provide some method to extend timeout maybe?

**Comment by leonardjohn** [comment]
We are experiencing the same problem too when we try to click "Reload tab" to reload stage view which we created via deep link from adaptive card.

**Comment by mustafasezer** [comment]
> Hi @shubh30126 @sumit12690 @miron4dev @mustafasezer
> 
> Did you solve the issue. Please reply. We're facing the same issue.

I just found a solution (at least for my case). I was using my domain name without "www" in front. It appears that if you do not have a subdomain, the app initialization times out. I changed the Application ID URI from being api://example.com to api://www.example.com and also the redirect URI. This solved the problem in my case, I am using `@microsoft/teams-js` version `2.4.1`.

How I came up with this: I was using tunnel for testing and AWS amplifyapp domain for "production". I checked today the DNS records and that did not help. All of a sudden I thought maybe it is because both amplifyapp and tunnel domains have subdomains, whereas the one I use is a so-called naked domain. I just tried it out and it worked

**Comment by kaneg** [comment]
As @mustafasezer said, he resolved the problem by changing domain name. And according to this issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1681, someone also mentioned the domain issue. So I guess, the domain is the key problem: the domain of the page where the SDK is initialized should be in the valid domains of the App manifest: "validDomains": []

**Comment by ScottRJones** [comment]
We are still experiencing the same error. 

We have created a new Teams project from scratch using the latest version of Visual Studio and Teams Toolkit. We are running the latest version of the teams-js npm in our main application and testing on the new version of Teams. 

After returning a MessagingExtensionResult with Type="Auth" and link to our login, our application launches correctly, the user logins in successfully, after which we call the following:
```
microsoftTeams.app.initialize().then(() => {
});
```

and get the **Uncaught (in promise) Error: SDK initialization timed out.** error.

We have tested in Edge, Chrome, Firefox and the Teams application itself, all with the same result.

We are using NGrok for local development but have also had the exact same result on a hosted server.

Our domain appears correct. It is listed in our valid domains (**** replaced with actual address):
```
  "validDomains": [
    "****.ngrok-free.app"
  ]
```

and in the OnTeamsMessagingExtensionFetchTaskAsync method:
```
                var output = new MessagingExtensionActionResponse
                {
                    ComposeExtension = new MessagingExtensionResult
                    {
                        Type = "auth",
                        SuggestedActions = new MessagingExtensionSuggestedAction
                        {
                            Actions = new List<CardAction>
                           {
                               new CardAction
                               {
                                   Type = ActionTypes.OpenUrl,
                                   Value = "https://****.ngrok-free.app/Login",
                                    Text = "Please sign in",
                                    Title = "Sign in", 
                               },
                            },
                        },
                    },
                };
```

@ChetanSharma-msft @nwojod-MSFT - Is this still being actively looked into by the Microsoft Team? 

@sommerlilie - Are you still experiencing the same issue as you were in March?

Thanks all
Scott

**Comment by tiennguyen1293** [comment]
We can  easy to reproduce on https://teams.microsoftonline.cn

Version: "@microsoft/teams-js": "^2.14.0"

Thanks all

**Comment by Nefiich** [comment]
I'm still having this issue. 
SDK fails to initialise inside the pop-up window while using ngrok for local development.

**Comment by Noext** [comment]
Any news on this ? Its 2024 and even with sso sample project it still bug randomly, it was working yesterday and today its not...

**Comment by KangxuanYe** [comment]
Hi @Noext and app developers,

We have identified some of issues might cause `SDK initialization times out` failure and are preparing instructions for developers so that you can resolve the issues by yourself. 

In the near term, we are also preparing a logger system so that we can have rich info to understand what exactly happened on your app at the time it fails on initialization. You can still reach us and we will have more clear and detailed explanation to you once the work is completed.

Thanks for reaching and the update will be coming soon.
