### ISSUE TITLE
Configuration of Connectors silently fail using new v2 SDK

### ISSUE THREAD

**Issue by wictorwilen** [OfficeDev/microsoft-teams-library-js#1191]
When trying to Save a custom Connector it fails without any error messages. I'm using the latest Promise based v2 SDK and when running the `page.config.setConfig` method the promise never resolves or rejects. After approx 5 seconds the Save button is enabled again with the message *Unable to save "myconnector" connector configuration. Please try again.*

Sample code
``` TypeScript
pages.config.registerOnSaveHandler((saveEvent: pages.config.SaveEvent) => {
    const settings: any = {
        entityId: "Something",
        contentUrl: `https://app.contoso.com/config?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}`
    };

    pages.config.setConfig(settings).then(() => { // <!-- This promise never resolves or reject
        pages.getConfig().then((setting: any) => {
             // get the webhook URL and persist
            }).catch(e => {
                saveEvent.notifyFailure(e);
            });
        }).catch(err => {
            console.error(err);
        });;
    }).catch(err => {
        console.error(err);
    });
});
```

**Comment by wictorwilen** [comment]
@Wajeed-msft, @v-chetsh - any update on this issue?

**Comment by v-chetsh** [comment]
@wictorwilen - We will check on it and get back to you.

**Comment by ChetanSharma-msft** [comment]
@wictorwilen - We have raised the bug for this issue and engineering team is looking into it.
Once we get any updates, we will share with you.

**Comment by jadahiya-MSFT** [comment]
@wictorwilen Sorry for the late response, we finished an investigation last month and found out that the endpoint communicated to on the Teams host was not properly resolving Promises. We've logged a bug with the team that owns that code and I will keep you posted on the status of it.

**Comment by koren-qualifico** [comment]
What’s the update on this?

**Comment by ChetanSharma-msft** [comment]
Hello @koren-qualifico - Sorry for delay in response.
Engineering team is looking into this issue and currently we don't have any ETA to share.
Once we get any update, we will inform you accordingly.

**Comment by Nivedipa-MSFT** [comment]
@wictorwilen - We have tested below code, and we are able to save the connector using new V2 SDK. Could you please check and confirm that its working for you or are you still facing the same issue?

```
    microsoftTeams.app.initialize().then(() => {
            microsoftTeams.app.getContext().then((context) => {
                TeamsTheme.fix(context);
            });
 microsoftTeams.pages.config.registerOnSaveHandler(function(saveEvent) {
                microsoftTeams.pages.config.setConfig({
                  entityId: "test",
                  contentUrl: "[ngrokURL]/connectorconfig",
                  configName: "test"
                });

                saveEvent.notifySuccess();
            });
              microsoftTeams.pages.config.registerOnRemoveHandler(function (removeEvent) {
                alert("remove");
            });
        });
```

**Comment by wictorwilen** [comment]
@Nivedipa-MSFT - It might work.... but that's neither following best practices for promises or as defined by your own documentation of the API.

The `setConfig`  method returns a Promsie and this is what the doc says *"@returns Promise that resolves when the operation has completed."*.  So, I would expect `saveEvent.notifySuccess()`  to be fired in that promise and not right after `setConfig` as your example shows. Otherwise, what's the point of having promises for `setConfig`?

This is how the code **should** look like:

``` TypeScript
 microsoftTeams.app.initialize().then(() => {
    microsoftTeams.app.getContext().then((context) => {
        TeamsTheme.fix(context);
    });
  microsoftTeams.pages.config.registerOnSaveHandler(function(saveEvent) {
        microsoftTeams.pages.config.setConfig({
          entityId: "test",
          contentUrl: "[ngrokURL]/connectorconfig",
          configName: "test"
        }).then(()=> {
           saveEvent.notifySuccess(); // this notification will guarantee that it's only happening when the save config is valid.
        });
    });
    microsoftTeams.pages.config.registerOnRemoveHandler(function (removeEvent) {
        alert("remove");
    });
  });
```

Can you please verify that ^this scenario works?

**Comment by heet-mehta** [comment]
Has there been any updates on this if this is resolved or not and which version to use?

**Comment by Nivedipa-MSFT** [comment]
@heet-mehta - We are actively checking the status of the bug with engineering team. We will let you know once we get any updates on it.

**Comment by xerosanyam** [comment]
@wictorwilen  do you face this issue on all the platforms?

**Comment by vilidou** [comment]
@xerosanyam we only noticed this issue on iOS (iphone and ipad). As a workaround, and until this is fixed properly in Teams SDKv2 or in Teams, we are using the code shared by @Nivedipa-MSFT on Nov28th (ie do not await `setConfig`)

**Comment by jadahiya-MSFT** [comment]
@wictorwilen We finally received notice that this issue should now be fixed on the Teams side, please let me know if this still repros and what environments it repros on.

**Comment by vilidou** [comment]
@jadahiya-MSFT - it still reproduces on iOS as of today (3/3 at 10am PST)

**Comment by jadahiya-MSFT** [comment]
@vilidou I only had confirmation that this was fixed on the Teams Web client. I will follow up with the iOS implementation and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@wictorwilen - Tested the bug fix on Teams Windows web client using TeamsJs library version 2.7.1.
The issue has fixed now.
Please refer below video:
[Bug Fix.webm](https://user-images.githubusercontent.com/92150070/232753060-51ae63ce-95b5-428d-88ec-54cbcf2894fc.webm)
