### ISSUE TITLE
"openExternal" device permission should also allow custom protocol handlers

### ISSUE THREAD

**Issue by divisumma18** [OfficeDev/microsoft-teams-library-js#1816]
The latest Teams updates appear to have dropped support for custom protocol handlers. We used a custom protocol to implement communication between our Teams tab and a desktop app we developed. This integration worked great for over a year but recently became totally useless as we are now unable to transfer data from Teams to the app.

So can you please restore support for custom protocol handlers?

Or can you suggest an alternative to achieve the same result?

Thank you.

**Comment by Prasad-MSFT** [comment]
@divisumma18 - Thanks for reporting this. We will check it with engineering team and will get back to you once we have any update.

**Comment by Prasad-MSFT** [comment]
@divisumma18 - We got update from engineering team that "The openExternal and notifications device permissions have always been a no-op in Teams."

**Comment by pbbr** [comment]
@Prasad-MSFT Are there any plans to activate custom protocols for the New Teams? The legacy Teams does support custom protocols if the permission was given by the user.

**Comment by Prasad-MSFT** [comment]
@pbbr - We have shared list of custom protocols to be added with engineering team and they are in process of adding these. Once its added, we will update you in this thread.
Thanks for understanding.

**Comment by pbbr** [comment]
@Prasad-MSFT Thanks for your feedback!

Why do you restrict the use of custom procotols even if the user has given the openExternal" permission? To be honest, for us (and a lot of other apps), deep linking out of Teams is essential to have a good user experience.

**Comment by Prasad-MSFT** [comment]
@divisumma18 , @pbbr - We got info from engineering team that this issue is resolved. Could you please check and update us?

**Comment by pbbr** [comment]
@Prasad-MSFT Unforunately, this issue isn't solved. We still get the following error: 

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/79220314/4e171555-dfd5-4d99-ab06-11c12a5651e9)
