### ISSUE TITLE
dialog.url.open not working in microsoft365 web client when changing tabs

### ISSUE THREAD

**Issue by ichivers** [OfficeDev/microsoft-teams-library-js#1962]
I have a Teams App with multiple tabs.  When in Microsoft365 web client (https://microsoft365.com) and changing tab the dialog.url.open in that tab doesn't work.  If I refresh the tab then it does work.  

**Note**: This does work in the Teams web client

I have reproduced this issue in this github repo:
https://github.com/ichivers/hello-world-tab-with-backend-dialog

It is based off this sample:
https://github.com/OfficeDev/TeamsFx-Samples/tree/v2.3.0/hello-world-tab-with-backend

I have added a 2nd Tab called Tab2, both Tab & Tab2 contain the following dialog code:

`const openDialog = () => {
    if(microsoftTeams.dialog.isSupported()){      
      const dialogSubmitHandler: microsoftTeams.dialog.DialogSubmitHandler = (result: any) => {
        console.log('dialog closed')
      }
      const baseUrl = `https://${window.location.hostname}:${window.location.port}`;
      const urlDialogInfo: microsoftTeams.UrlDialogInfo = {
        url: baseUrl + "/index.html#/privacy",
        title: "Privacy",
        size: {
          height: 650,
          width: 1224
        }        
      };
      microsoftTeams.dialog.url.open(urlDialogInfo, dialogSubmitHandler)
    }
  }`

Which is called from a button

`<button onClick={openDialog}>Open dialog</button>`

Run the app and the Open dialog button will work on the 'Personal Tab' but when you switch to 'Tab2' it won't open.  If you refresh Tab2 then it will work.

**Comment by sayali-MSFT** [comment]
@ichivers - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@ichivers -We are able to repro the issue, we have raised the bug for the same. We will let you know once we have any update.

**Comment by ichivers** [comment]
This also happens in the Outlook web client.

**Comment by lakhveerk** [comment]
Hi Ian! 

Upon our initial investigation, we've identified that tabs whose contentUrls differ only in the fragment identifier (the part after the #) are leading to unexpected behaviors.

To unblock yourself in your test app, you can differentiate the content URLs in the manifest by specifying the unique query parameters, such as "${{TAB_ENDPOINT}}/index.html?B#/tabB" and "${{TAB_ENDPOINT}}/index.html?A#/tabA". This will auto reload the page and APIs will work as expected.

We are actively working on the issue and will keep you updated on our progress. Please don't hesitate to reach out if you have any further questions.

**Comment by lakhveerk** [comment]
Hi @ichivers 
The bug has been fixed in both Outlook and Microsoft365. Please let us know if you continue to experience any problem.

**Comment by anurag-jaiswal18** [comment]
Hey @lakhveerk
Same issue still replicable with teams-js@2.22.0
 is this fix available with any specific library ?

**Comment by lakhveerk** [comment]
Hi @ichivers
The fix is not specific to any teams-js version. So you are good there. 
I created a similar app from [here](https://github.com/OfficeDev/TeamsFx-Samples/tree/v2.4.0/hello-world-teams-tab-and-outlook-add-in), and dialogs are working fine on tab switching in both Outlook and Microsoft365 web. You can see it in this video below. If the issue is persisting for you, please help me repro the issue. I created an app with the above link and added a second tab in it just like you have. What should I do differently to see the same behavior? 
Here is a small video that I created to show that it is working for me
https://github.com/OfficeDev/microsoft-teams-library-js/assets/88564543/96d0edd1-d697-4399-b47a-67af43a8f12d
