### ISSUE TITLE
clipboard.write(...) throws internal error (500) in personal tab

### ISSUE THREAD

**Issue by thierschi** [OfficeDev/microsoft-teams-library-js#2353]
I want to copy text to a user's clipboard. In the past I implemented this using the clipboard-api from teams-js. Recently this stopped working.

I tried the function in a simple button to eliminate errors on my side and made a simple button for testing:
```ts
<Button
    onClick={async () => {
        try {
            if (clipboard.isSupported()) {
                const blob = new Blob(["Hello"], {
                    type: "text/plain",
                });
                await clipboard.write(blob);
            }
        } catch (e) {
            console.error(e);
        }
    }}
>
    Test
</Button>
```
When trying to run this, `clipboard.write(...)` throws the following error:
```json
{
    "errorCode": 500,
    "message": "An internal error occurred"
}
```
I've tested this in the Teams v2 Mac-App and on the web in Chrome, both show the same behaviour. In Chrome I also made sure that the teams website has access to my clipboard.
Debugging into the `clipboard.write()` function didn't give me any hints. Maybe an issue on the receiving side of the message mechanism.

```
@microsoft/teams-js: 2.23.0
Teams-Version Mac-App: 24124.1411.2908.8258.
Teams-Version Web: 1415/24051622207
```

**Comment by Nivedipa-MSFT** [comment]
@thierschi - Thanks for reporting your issue. We are checking this internally, we will update you soon.

**Comment by shrshindeMSFT** [comment]
Thank you for reporting this issue @thierschi. We will update this thread as soon as we have a fix for this bug.

**Comment by ZimnitskiYury** [comment]
also some notes from #2196 

microsoft/teams-js: 2.24.0
Microsoft Teams version: 24137.2216.2931.2440
The client version is 49/24050307617.

if i write to clipboard image:

- web teams works fine
- desktop throws error Failed to copy to clipboard. NotAllowedError: Failed to execute 'write' on 'Clipboard': Document is not focused.

if I write to clipboard text/plain or text/html:

- web and desktop teams throw Internal Error

**Comment by shrshindeMSFT** [comment]
Update: 
There is a fix deployed for `clipboard.write() ` throwing internal error on web and desktop. Also, there is some work going on regarding the `Clipboard: Document is not focused`. We will keep updating this thread as we get closer to resolving this issue. Thank you for your patience.

**Comment by MrKSchmitz** [comment]
Any traction on a fix for this?
Both this ticket and the linked one says there's a fix deployed. But this is still an issue in Teams+Desktop

**Comment by ali-ms** [comment]
Hi @MrKSchmitz , thanks for following up on this. While we're still looking into this, a suggested workaround today is to use the [HTML5 `clipboard.write()` API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write), which should work for your apps on Teams desktop as well as Teams web. Please give it a try and let us know if you still have issues. Thanks!
