### ISSUE TITLE
`setConfig` does not save the given `contentUrl` on Teams V2 client

### ISSUE THREAD

**Issue by melsener** [OfficeDev/microsoft-teams-library-js#2370]
Hi,
I am having an issue saving the `contentUrl` in config after creating a new connector. Could you assist with this issue?

Steps to reproduce:
1. Create a connector
2. Create new settings (including `contentUrl`) after receiving the webhook URL and save it by calling `setConfig`
3. Click on the "Manage channel" menu item from the channel menu and click on "Edit" in the "Connectors" section
4. Click on the "Configured" tab and click on "Configured > Manage" on the new connector
5. Log current settings by calling `getConfig`

Expected Result:
- `contentUrl` is equal to what's been given.

Actual Result:
- The `contentUrl` does not match what was given. It is equal to the `configurationUrl` in the manifest file. 
- The given `entityId` and `configName` are being correctly set with the `setConfig` call.

Notes:
- It was working as expected in the legacy Teams app. 
- Tried both with `"@microsoft/teams-js": "^1.11.0"` and `"@microsoft/teams-js": "^2.19.0"`

**Comment by Nivedipa-MSFT** [comment]
@melsener - Thanks for reporting your issue. We are checking this internally, we will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@melsener - We already have an incident created for this issue. We will keep you posted on the updates. Thank you.

**Comment by Nivedipa-MSFT** [comment]
@melsener - We got an update from engineering team that incident has fixed now. Could you please test this and confirm once?

**Comment by melsener** [comment]
@Nivedipa-MSFT I have just tested it on the web client, but unfortunately, the issue is still occurring. please let me know if I can provide more information for you.

**Comment by melsener** [comment]
@Nivedipa-MSFT unfortunately, the issue is still there. could you help?

**Comment by melsener** [comment]
@Nivedipa-MSFT any updates on this?

**Comment by aykutbulca** [comment]
@Nivedipa-MSFT, can you please share an update on this? Microsoft [released a guideline ](https://learn.microsoft.com/en-us/microsoftteams/m365-custom-connectors#update-connectors-url)on how to update existing webhook URLs as a part of connector migration, but it doesn't work due to this issue. It is blocking our users tdoing the required change.

**Comment by aykutbulca** [comment]
@Nivedipa-MSFT, can you please share any updates?

**Comment by patriotyk** [comment]
@erinha @Nivedipa-MSFT Any updates? We are experiencing the same issue. 
But what I have found that it is not an issue with saving. If we save config in v2 client, and then open our connector in msteams web client, it works as expected and opens saved  `contentUrl ` But when open in v2 client, it opens our connector with `configurationUrl ` so looks like v2 client is not able to find saved configuration.

**Comment by Nivedipa-MSFT** [comment]
We understand your concern. We are actively checking with the engineering team for any updates on the issue. While there are no new updates at this time, we will inform you as soon as we have more information. 

We appreciate your patience and understanding in the meantime. Thank you for bringing this to our attention.
