### ISSUE TITLE
Unexpected login popup triggered by app.initialize in New Outlook

### ISSUE THREAD

**Issue by zumbuschms** [OfficeDev/microsoft-teams-library-js#2459]
We are working on a Tab App to be added to all supported Outlook versions. The app accesses an on-prem web application via side loading the app into a Microsoft 365 tenant. As we need to support external OpenID Connect providers as well as Microsoft 365, we went for the authentication.authenticate approach and this works as expected. During initialization of our web application, we call app.initialize() and app.getContext() to retrieve the user's name as a hint for our login dialog.

Wenn calling app.initialize in New Outlook context, an Microsoft 365 login popup is shown which is unexpected, as we don't want to use signle sign on capabilities. Logging in using my Microsoft 365 credentials I get the following error message: 
![image](https://github.com/user-attachments/assets/4171a8a8-281a-4769-92a6-c991c5d4646e)

This only occurs within New Outlook and not within legacy Outlook or Outlook on the Web.

Really confusing about the error message is that the IDs in the error message represent Outlook on the Web (bc59ab01-8403-45c6-8796-ac3ef710b3e3) and Office 365 Exchange Online (00000002-0000-0ff1-ce00-000000000000). Our web application does not access any Microsoft and just connects to our on-prem deployed backend application.

How do we get rid of the login prompt?

Our Environment: 
- Windows 11
- New Outlook 1.2024.725.400
- Microsoft 365 Developer tenant
- TeamsJS 2.25
- Manifest v.1.16

**Comment by Nivedipa-MSFT** [comment]
@zumbuschms - Thanks for reporting your issue. We will check this and update you soon.

**Comment by salaman** [comment]
@zumbuschms I believe this was fixed last week. Can you try relaunching Outlook a few times to pick up the new version, and also include the "Client version" from the settings > general > about page if it hasn't fixed it?

**Comment by zumbuschms** [comment]
The issue still occurs and I only started to use New Outlook last week to test our app. My current version of New Outlook:

You have Microsoft Outlook Version 1.2024.725.400 (Production).
Client Version is 20240802003.17.
WebView2 Version is 127.0.2651.98.

**Comment by salaman** [comment]
We haven't been able to reproduce this issue internally. We have many apps that call `app.initialize()` successfully even if they are not configured for Tab SSO and I'm not seeing the prompting occur. That would happen if you're calling `authentication.getAuthToken(...)` to trigger a non-silent request -- can you share any code snippets or some minimal repro code that you know is, by itself, causing this prompt to show?

**Comment by zumbuschms** [comment]
I was able to reproduce the popup with a simple sample application in the latest New Outlook using TeamsJS 2.26.

Outlook Version: 1.2024.814.200 (Production)
Client Version: 20240816003.13
WebView2 Version is 127.0.2651.105

I've attached a zip file with the sample app and a Dockerfile to host the app in nginx. [app.zip](https://github.com/user-attachments/files/16749978/app.zip). You need to place a certificate file (cert.crt) and its private key (cert.key) in the folder config/tls to be able to build and run the Docker container.

We can reproduce the issue on multiple systems wiht multiple MS365 tenants. The affected environments:

Common:
- App URL: https://localhost:8462/app/

Env 1:
- Windows 11
- Member of an Azure Hybrid Active Directory (corporate tenant)
- App deployed to a different tenant (developer tenant No 1)
- Outlook configured to connect to a single mailbox in developer tenant No 1

Env 2:
- Windows Server 2022
- Joined to Active Directory (standalone AD)
- App deployed to developer tenant No 1
- Outlook configured to connect to a single mailbox in developer tenant No 1

Env 3:
- Windows 10
- Member of an Azure Hybrid Active Directory (corporate tenant)
- App deployed to a different tenant (developer tenant No 2)
- Outlook configured to connect to a single mailbox in developer tenant No 2

**Comment by zumbuschms** [comment]
Are there any updates on this issue? We can still reproduce the issue on current version of new Outlook.

OS Version: Windows 11 Enterprise 22H2 (OS Build 22621.4602)
Microsoft Outlook Version: 2.2025.109.100 (Production)
Client Version: 20250103002.15
WebView2 Version: 131.0.2903.112

**Comment by erinha** [comment]
Hi @zumbuschms, thanks for the update. Can you please enable teams-js logging as described in this page and share the teams-js client logs (feel free to remove auth tokens or any other personal details)?

https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging

Thanks.

**Comment by salaman** [comment]
Can you also upload the latest `%LOCALAPPDATA%\Microsoft\Olk\logs\olk_*.log` file generated after a repro? I tried to recreate your environment again with the same app URL and could not repro the issue.

**Comment by zumbuschms** [comment]
I was again able to reproduce the issue with the sample application I posted in August. Although I followed the instructions for Teams logging, there was no log output from teamsJs. Here is the Outlook log file: [olk_20250115_085404100.log](https://github.com/user-attachments/files/18421538/olk_20250115_085404100.log)

**Comment by salaman** [comment]
Sorry for the delay here, I think I found the issue and am working on a fix this week which should hopefully resolve this by the end of next week (due to Outlook deployment schedules). Thanks for providing the logs.
